name: 'PR Annotate Regex'
description: 'Annotate pull requests based on regex findings in added lines'
inputs:
  github-token:
    description: 'GitHub token for API calls (optional; falls back to GITHUB_TOKEN env var)'
    required: false
  rules:
    description: 'JSON array of rule objects, each with fields: regex, message (supports {regex}, {line}, {match}), level (optional, default: warning), and paths (optional, regex patterns for file filtering)'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
