name: 'PR Annotate Regex'
description: 'Annotate pull requests based on regex findings in added lines'
inputs:
  github-token:
    description: 'GitHub token for API calls'
    required: true
  rules:
    description: 'JSON array of rule objects, each with fields: regex, annotation-level, message, and optional paths (regex patterns for file filtering)'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
