name: 'Regex PR Annotator'
description: 'Annotate pull requests based on regex findings in added lines'

branding:
  icon: 'align-left'
  color: 'yellow'

inputs:
  github-token:
    description: 'GitHub token for API calls (optional; falls back to GITHUB_TOKEN env var)'
    required: false
  rules:
    description: 'JSON array of rule objects, each with fields: regex, message (supports {regex}, {line}, {match}), level (optional, default: warning), and paths (optional, regex patterns for file filtering)'
    required: true
  debug:
    description: 'Enable debug logging: outputs patches and match info'
    required: false
    default: 'false'
  fail_level:
    description: 'Minimum level (notice, warning, error) that causes the action to fail. Use "none" to never fail.'
    required: false
    default: 'none'

runs:
  using: 'node20'
  main: 'dist/index.js'
