name: Local Test PR Annotate Regex

on:
  workflow_dispatch:
  pull_request:

jobs:
  annotate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - run: |
          pwd
          ls -la

      - name: Run PR Annotate Regex (JSON rules)
        uses: ./
        if: always()
        with:
          fail_level: 'error'
          rules: |
            [
              {"regex": "TODO", "message": "Found TODO: {line}", "paths": ["\\.js$"]},
              {"regex": "console\\.log", "level": "error", "message": "Avoid console.log usage on commited code"}
            ]

      - name: Run PR Annotate Regex (JS file rules)
        uses: ./
        if: always()
        with:
          fail_level: 'error'
          rules: test/rules-sample.js
