name: Local Test PR Annotate Regex

on:
  workflow_dispatch:
  pull_request:

jobs:
  annotate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run PR Annotate Regex
        uses: ./
        with:
          rules: |
            [
              {"regex": "TODO", "message": "Found TODO: {line}", "paths": ["\\.js$"]},
              {"regex": "console\\.log", "level": "error", "message": "Avoid console.log usage on commited code"}
            ]
